### ISSUE TITLE
Using the meshes in other GL libraries like ThreeJs

### ISSUE THREAD

**Issue by venidev** [frenchtoast747/webgl-obj-loader#2]
Thanks for the obj loader, very helpful library.
Is it possible to use the Mesh in other libraries like ThreeJS?

**Comment by frenchtoast747** [comment]
ThreeJS supplies its own OBJ and MTL loaders that work well with ThreeJS, so this issue will not be worked. The focus of this library is to be a simple parser/loader specifically for the OBJ/MTL formats and should be structured in such a way that helps facilitate the learning of WebGL and its underlying shading languages.
