### ISSUE TITLE
Support N-gons in an OBJ model

### ISSUE THREAD

**Issue by frenchtoast747** [frenchtoast747/webgl-obj-loader#25]
Currently, if a model has more than 4 vertices in a face, the model will not load correctly and will have gaps. To prevent this from happening, the model first needs to be pre-processed and triangulated to make it WebGL happy.

This is somewhat of a pain for people wanting to learn WebGL, but not care about how model files are laid out (or how to use some third party program to pre-process the file).

Instead, the model should be converted to triangles on the fly.

**Comment by sjfricke** [comment]
I have been looking into and after testing it out on multiple different models I have found how to draw each triangle for 5 vertices faces.

f 1 2 3 4 5

This can be successfully drawn with the combination:
1 2 3
1 3 4 
1 4 5

So you can just have it grab the faceIndex[0] each time and combine it with faceIndex[1 + i] and faceIndex[2 + i] where "i" is looped from 0 to 2

**Comment by qtip** [comment]
We should have the library emit a warning message with a description of the problem and suggestions for fixing it at the very least.

**Comment by frenchtoast747** [comment]
Support for N-gons has been added in [v2.0.3](https://github.com/frenchtoast747/webgl-obj-loader/releases/tag/v2.0.3)
