### ISSUE TITLE
Multiple textures

### ISSUE THREAD

**Issue by thmundal** [frenchtoast747/webgl-obj-loader#26]
How do I handle a model with multiple textures? Is there a way to know what texture-coordinates a specific texture should have on the model?

For example, a horse, where the tail is a seperate texture, or a man with a hat

**Comment by qtip** [comment]
I believe this would need mtl support which seems to be under development. @frenchtoast747 eta for mtl support?

**Comment by frenchtoast747** [comment]
I apologize, @thmundal, there isn't support for that yet. But, as @qtip has said, I have started work for .mtl support which will provide the information needed. I'm not sure how long it will take me to complete as I can only work on it in my free time and I haven't had much of that lately.

**Comment by frenchtoast747** [comment]
Once all issues with the mtl-support-v2 label are completed, this issue will be complete. I'm going to go ahead and close this issue since it will be completed as a part of several others.
