### ISSUE TITLE
Webpack Loader

### ISSUE THREAD

**Issue by mentos1386** [frenchtoast747/webgl-obj-loader#43]
Hey, awesome job on loader!

I'm working on a project that is using webpack. I couldn't find any webpack loaders for obj files, so i made my own which just calls this library `new Mesh(source)`. Just want to leave this here for people that are using webpack.

[webpack-obj-loader](https://github.com/mentos1386/webpack-obj-loader)

**Comment by frenchtoast747** [comment]
Awesome! Thanks @mentos1386, I'll update the README to point to it, soon.

**Comment by frenchtoast747** [comment]
Updated the README to point to webpack-obj-loader.
