### ISSUE TITLE
Add support for more than 4 vertices per face

### ISSUE THREAD

**Issue by mnoven** [frenchtoast747/webgl-obj-loader#45]
Right now the lib seems to convert quads to triangles and thus assumes 3 or 4 vertices per face. The .obj format has however no limit on how many vertices there should be per face and some models break because of this. 

An example of an .obj which sometimes has more than 4 vertices per face rendered in my engine using `gl.drawElements`:

![broken](https://user-images.githubusercontent.com/31854261/35224843-b05d1ae0-ff86-11e7-891c-c3e48afd6d04.png)

(Model taken from https://casual-effects.com/g3d/data10/research/model/breakfast_room/breakfast_room.zip)

**Comment by qtip** [comment]
That's absolutely something that the lib should support, thank you for filing this issue. It's non-trivial, but there are some well known algorithms to do this (see https://en.wikipedia.org/wiki/Polygon_triangulation).

@frenchtoast747: The code for the quad triangulation should be tossed and a generic triangulation function should take its place:

```
for each face in faces:
    for each triangle in triangulate(faces):
        // ....
```

Here are baby steps:

- [ ] Implement `triangulate(...)` as a quad2tri algorithm
- [ ] Replace current quad2tri logic with `triangulate(...)` inside of constructor
- [ ] Reimplement `triangulate(...)` with the a proper triangulation algorithm

**Comment by tckxjzc** [comment]
### +1

**Comment by frenchtoast747** [comment]
Added [v2.0.3](https://github.com/frenchtoast747/webgl-obj-loader/releases/tag/v2.0.3) which provides initial support for N-gons. I will create another issue to provide a better `triangulate()` algorithm.

**Comment by dekdevy** [comment]
Much appreciated. I will report back with any potential issues.
