### ISSUE TITLE
Add support for calculating tangents and bitangents

### ISSUE THREAD

**Issue by michaelnoven** [frenchtoast747/webgl-obj-loader#47]
With the existing support for .mtl files it would make sense for the library to calculate the tangents and bitangents as an option. These are later needed for calculating the TBN matrix when dealing with [normal maps](http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-13-normal-mapping/). 

The tangents and bitangents are derived from the vertices positions and (most commonly) the direction of the texture coordinates.

**Comment by frenchtoast747** [comment]
Closing as completed, thanks to @michaelnoven!
