### ISSUE TITLE
UV layout, error in the code.

### ISSUE THREAD

**Issue by dybiszb** [frenchtoast747/webgl-obj-loader#55]
Hi there, I just spotted that (webgl-obj-loader.js; line 866):
                         _case _layout.Layout.UV.key:
                                dataView.setFloat32(offset, this.textures[i * 2], true);
                                dataView.setFloat32(offset + 4, this.**vertices**[i * 2 + 1], true);_

probably should look like
                         _case _layout.Layout.UV.key:
                                dataView.setFloat32(offset, this.textures[i * 2], true);
                                dataView.setFloat32(offset + 4, this.**textures**[i * 2 + 1], true);_

which seems to solve a small problem that I had with correct gBuffer mappings ; D

**Comment by frenchtoast747** [comment]
Thanks, @dybiszb, for finding the issue and reporting!

Fixed on master.

**Comment by dybiszb** [comment]
No problem - my pleasure ; )
