### ISSUE TITLE
Missing TypeScript header file

### ISSUE THREAD

**Issue by DCtheTall** [frenchtoast747/webgl-obj-loader#58]
This module is currently missing and `index.d.ts` file which means that it is not compatible with TypeScript without type casting to `any` type, which removes the benefit of the static typing.

If any maintainer of this repo is interested, I would be happy to open a PR to add one?

**Comment by frenchtoast747** [comment]
I've actually contemplated on converting the whole library over to TS and would gladly accept  a type def file for now until that can happen. Feel free to create a PR and I'll pull it in. Thanks!

**Comment by DCtheTall** [comment]
One way I was thinking of generating the `.d.ts` file is to translate the working JavaScript into TypeScript then use Webpack to generate type defs automatically. Would including any of the translated JS be helpful?

**Comment by frenchtoast747** [comment]
I think I'm going to spend a couple of hours today and just go ahead and do the TS conversion. Standby.

**Comment by frenchtoast747** [comment]
Took me longer than I thought, but I updated everything to be TS and included the .d.ts files along side the main library. Let me know if I borked something up. Thanks!
