### ISSUE TITLE
error

### ISSUE THREAD

**Issue by haroel** [frenchtoast747/webgl-obj-loader#62]
1.  download the same image mutiple times, you can get all images paths and set in the hashmap, then，download in queue;
2. error check filename( see below)

**Comment by haroel** [comment]
it should be this 


```

for (const materialName in mtl.materials) {
                    if (!mtl.materials.hasOwnProperty(materialName)) {
                        continue;
                    }
                    const material = mtl.materials[materialName];
                    for (const attr of mapAttributes) {
                        const mapData = material[attr];
                        if (!mapData **|| !mapData.filename** ) {
                            continue;
                        }


```

**Comment by frenchtoast747** [comment]
Hi @haroel, thank you for filing this issue.

I'm not quite understanding. Could you provide the error that is occurring either by pasting the text or a screenshot of the console error?

**Comment by frenchtoast747** [comment]
Closing, unless more information can be provided.
