### ISSUE TITLE
Wrong parsing when faces is quade with uv

### ISSUE THREAD

**Issue by dimensi** [frenchtoast747/webgl-obj-loader#69]
If you export a model with quads and texture coordinates, you will see artifacts. 
![image](https://user-images.githubusercontent.com/11390039/68026591-3fc0d300-fcc1-11e9-8efb-78b002a3ee31.png)
But if all the quads are converted to triangles when exporting in advance, there are no problems.
![image](https://user-images.githubusercontent.com/11390039/68026601-494a3b00-fcc1-11e9-9980-4d77680c6c4e.png)
You can check it in the sandbox
https://codesandbox.io/s/apple-webgl-u4pg7
You can also check model in [obj viewer](https://3dviewer.net/).

**Comment by dimensi** [comment]
Merge this please https://github.com/frenchtoast747/webgl-obj-loader/pull/66

**Comment by frenchtoast747** [comment]
Thanks for reporting! I've merged in those changes. Please let me know if there is anything else.
